### ISSUE TITLE
Plugin stops working after auto-upgrade

### ISSUE THREAD

**Issue by max-baz** [cerebroapp/cerebro-basic-apps#2]
After the plugin is auto-upgraded, I don't see any apps in search results. Restarting Cerebro helps.
This is the second time I see this happening with `cerebro-basic-apps`, now again with v1.0.8.

This is the log from background window:

```
Run plugins autoupdate
background.bundle.js:1 [npm] Install package cerebro-basic-apps
background.bundle.js:1 Version: 1.0.8
background.bundle.js:1 Extract https://registry.npmjs.org/cerebro-basic-apps/-/cerebro-basic-apps-1.0.8.tgz to /home/maximbaz/.config/Cerebro/plugins/node_modules/cerebro-basic-apps
background.bundle.js:1 Download and extract to temp path: /tmp/cerebro-basic-apps
background.bundle.js:1 [npm] Uninstall package cerebro-basic-apps
background.bundle.js:1 Remove package directory  /home/maximbaz/.config/Cerebro/plugins/node_modules/cerebro-basic-apps
background.bundle.js:1 Update package.json
background.bundle.js:1 Rewrite package.json
background.bundle.js:1 Move /tmp/cerebro-basic-apps to /home/maximbaz/.config/Cerebro/plugins/node_modules/cerebro-basic-apps
background.bundle.js:1 [cerebro-basic-apps] Plugin removed
background.bundle.js:1 Add package to dependencies
background.bundle.js:1 1 plugins are updated
background.bundle.js:1 Done! Sending data back to main window
background.bundle.js:1 [rpc] send plugin.message
[cerebro-basic-apps] Update plugin
[cerebro-basic-apps] Plugin updated
background.bundle.js:1 Done! Sending data back to main window
background.bundle.js:1 [rpc] send plugin.message
background.bundle.js:1 Done! Sending data back to main window
background.bundle.js:1 [rpc] send plugin.message
```

This is the log from main window:

```
[cerebro-basic-apps] Plugin removed
/usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1 [rpc] emit plugin.message
/usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1 Uncaught TypeError: Cannot read property 'onMessage' of undefined
    at EventEmitter.n.i (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1:261580)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at EventEmitter.r.ipcRenderer.on (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1:99707)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
/usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1 [rpc] emit plugin.message
/usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1 Uncaught TypeError: Cannot read property 'onMessage' of undefined
    at EventEmitter.n.i (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1:261580)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at EventEmitter.r.ipcRenderer.on (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1:99707)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
/usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1 [rpc] emit plugin.message
/usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1 Uncaught TypeError: Cannot read property 'onMessage' of undefined
    at EventEmitter.n.i (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1:261580)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at EventEmitter.r.ipcRenderer.on (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1:99707)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
/usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1 Uncaught TypeError: Cannot read property 'plugin' of undefined
    at t.e (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1:767955)
    at t.e (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1:768252)
    at Object.select (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1:766128)
    at t.e (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1:767080)
    at Object.i (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1:127990)
    at h (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1:123196)
    at Object.v [as executeDispatchesInOrder] (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1:123444)
    at p (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1:54506)
    at h (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:1:54647)
    at Array.forEach (native)
main.bundle.js:1 [rpc] emit plugin.message
main.bundle.js:1 Uncaught TypeError: Cannot read property 'onMessage' of undefined
    at EventEmitter.n.i (main.bundle.js:1)
    at emitOne (events.js:96)
    at EventEmitter.emit (events.js:188)
    at EventEmitter.r.ipcRenderer.on (main.bundle.js:1)
    at emitTwo (events.js:106)
    at EventEmitter.emit (events.js:191)
n.i @ main.bundle.js:1
emitOne @ events.js:96
emit @ events.js:188
r.ipcRenderer.on @ main.bundle.js:1
emitTwo @ events.js:106
emit @ events.js:191
```

**Comment by ogustavo-pereira** [comment]
@maximbaz what operating system are you using?

**Comment by max-baz** [comment]
Hello, this is a very old issue and given that I don't use the app anymore nor there are any upvotes indicating that others had the same issue, let's just close the ticket.
